### ISSUE TITLE
Problem with ecef2ned

### ISSUE THREAD

**Issue by CarstenB8** [NavPy/NavPy#22]
Dear developers,

I just checked out your project today, because I am interested in GPS satellite tracking.
I possibly found a bug, but maybe I am using your code wrong.
I performed a basic test: I transformed a GPS position from LLA to ECEF
Then transformed directly from ECEF to NED and also from ECEF to LLA to NED

The results are different.

example:

import numpy as np
import navpy

lat=np.array(45.,dtype='float64')
lon=np.array(16.1,dtype='float64')
h=np.array(50.,dtype='float64')

eGPS=navpy.lla2ecef(lat, lon, 13000*1000,latlon_unit='deg', alt_unit='m', model='wgs84')
ecef2ned=navpy.ecef2ned(eGPS,lat,lon,h,latlon_unit='deg', alt_unit='m', model='wgs84')
test=navpy.ecef2lla(eGPS,latlon_unit='deg')
ecef2lla2ned=navpy.lla2ned(test[0],test[1],test[2],lat, lon, h,latlon_unit='deg', alt_unit='m',  model='wgs84')

result:
ecef2lla2ned=2.980232238769531250e-08 9.313225746154785156e-10 -1.999995000003606081e+07

ecef2ned= -2.138465560481697321e+04 0.000000000000000000e+00 -2.636745363451633602e+07

ecef2lla2ned is correct from my point of view.
ecef2ned seems to be off.#
The navpy.ecef2ned function does not seem to use the altitude value h at all, I can change h randomly with no change in result.
BTW: this is my first GitHub contribution, please don't kill me. :)

Best regards,
Carsten

**Comment by CarstenB8** [comment]
this problem was already raised earlier.

**Comment by hamid-m** [comment]
@CarstenB8 , thanks for taking time to raise the issue!  I assume Issue #16 addressed the question you had.  Is that correct?  Just want to the list the correct issue so the next person can find the solution.  If you think this is still a bug, then we should keep the issue open for further conversation.  Otherwise perhaps we need to revisit the documentation to make this distinction clear.
